sudo: required
language: node_js
node_js:
  - "7"
branches:
  only:
    - master
before_install:
  - cd src/environments
  - rm -rf environment.prod.ts
  - openssl aes-256-cbc -K $encrypted_0678684cbf21_key -iv $encrypted_0678684cbf21_iv -in environment.prod.ts.enc -out environment.prod.ts -d
  - cd ../../
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN